[package]
name = "sc-genesis-builder"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate GenesisConfig builder helpers"
readme = "README.md"

[dependencies]
frame-support = { version = "4.0.0-dev", default-features = false, path = "../../frame/support" }
serde_json = { version = "1.0.85", default-features = false, features = ["alloc"] }
sp-api = { version = "4.0.0-dev", default-features = false, path = "../../primitives/api" }
sp-genesis-builder = { version = "0.1.0-dev", default-features = false, path = "../../primitives/genesis-builder" }
sp-runtime = { version = "24.0.0", default-features = false, path = "../../primitives/runtime", features = ["serde"] }
sp-std = { version = "8.0.0", default-features = false, path = "../../primitives/std" }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"serde_json/std",
	"sp-api/std",
	"sp-genesis-builder/std",
	"sp-runtime/std",
	"sp-std/std",
]
